# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/NexysA7Con.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LED_IO_0_0/design_1_LED_IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LED_IO_0_0 || ORIG_REF_NAME==design_1_LED_IO_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SWITCH_IO_0_0/design_1_SWITCH_IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SWITCH_IO_0_0 || ORIG_REF_NAME==design_1_SWITCH_IO_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CustomClock_0_0/design_1_CustomClock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_CustomClock_0_0 || ORIG_REF_NAME==design_1_CustomClock_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Button_IO_0_0/design_1_Button_IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Button_IO_0_0 || ORIG_REF_NAME==design_1_Button_IO_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
