# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/NexysA7Con.xdc

# Block Designs: bd/TOP/TOP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP || ORIG_REF_NAME==TOP} -quiet] -quiet

# IP: bd/TOP/ip/TOP_LED_IO_0_0/TOP_LED_IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_LED_IO_0_0 || ORIG_REF_NAME==TOP_LED_IO_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_SWITCH_IO_0_0/TOP_SWITCH_IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_SWITCH_IO_0_0 || ORIG_REF_NAME==TOP_SWITCH_IO_0_0} -quiet] -quiet

# XDC: bd/TOP/TOP_ooc.xdc
